var GAME = {
   VARIABLES : {},  // values are changeable while game is running (inside main.js file > _resetGameVariables func)
   INIT_SPEED : .00035,
   INCREMENT_SPEED_BY_TIME : .0000025,
   INCREMENT_SPEED_BY_LEVEL:.000005,
   DISTANCE_FOR_SPEED_UPDATE:100,

   RATIO_SPEED_DISTANCE: 50,
   RATIO_SPEED_ENERGY: 3,

   DISTANCE_FOR_LEVEL_UPDATE: 1000,

   PLANE_DEFAULT_HEIGHT: 100,
   PLANE_AMP_HEIGHT: 80,
   PLANE_AMP_WIDTH: 75,
   PLANE_MOVE_SENSIVITY: 0.005,
   PLANE_ROTX_SENSIVITY: 0.0008,
   PLANE_ROTZ_SENSIVITY: 0.0004,
   PLANE_MIN_SPEED: 1.2,
   PLANE_MAX_SPEED: 1.6,

   SEA_RADIUS: 600,
   SEA_LENGTH: 800,
   WAVES_MIN_AMP : 5,
   WAVES_MAX_AMP : 20,
   WAVES_MIN_SPEED : 0.001,
   WAVES_MAX_SPEED : 0.003,

   CAMERA_FAR_POS: 500,
   CAMERA_NEAR_POS: 150,
   CAMERA_SENSITIVTY: 0.002,

   COIN_DISTANCE_TOLERANCE: 15,
   COIN_VALUE: 3,
   COINS_SPEED: .5,
   DISTANCE_FOR_COINS_SPAWN: 100,

   ENEMY_DISTANCE_TOLERANCE: 10,
   ENEMY_VALUE: 10,
   ENEMIES_SPEED: .6,
   DISTANCE_FOR_ENEMIES_SPAWN: 50
};

module.exports = GAME;