var GAME = {
   VARIABLES : {
      ENERGY: 100,
      PLANE_COLLISION_SPEED_X:0,
      PLANE_COLLISION_SPEED_Y:0,
      LEVEL:1,
      SPEED_LAST_UPDATE:0,
   },
   SPEED : 0,
   INIT_SPEED : .00035,
   BASE_SPEED : .00035,
   TARGET_BASE_SPEED : .00035,
   INSERT_SPEED_BT_TIME : .0000025,
   INSERT_SPEED_BT_LEVEL:.000005,
   DISTANCE_FOR_SPEED_UPDATE:100,
   // SPEED_LAST_UPDATE:0,

   DISTANCE:0,
   RATIO_SPEED_DISTANCE:50,
   ENERGY:100,
   RATIO_SPEED_ENERGY:3,

   // LEVEL:1,
   LEVEL_LAST_UPDATE:0,
   DISTANCE_FOR_LEVEL_UPDATE:1000,

   PLANE_DEFAULT_HEIGHT:100,
   PLANE_AMP_HEIGHT:80,
   PLANE_AMP_WIDTH:75,
   PLANE_MOVE_SENSIVITY:0.005,
   PLANE_ROTX_SENSIVITY:0.0008,
   PLANE_ROTZ_SENSIVITY:0.0004,
   PLANE_FALL_SPEED:.001,
   PLANE_MIN_SPEED:1.2,
   PLANE_MAX_SPEED:1.6,
   PLANE_Speed:0,

   PLANE_COLLISION_DISPLACEMENT_X:0,
   // PLANE_COLLISION_SPEED_X:0,

   PLANE_COLLISION_DISPLACEMENT_Y:0,
   // PLANE_COLLISION_SPEED_Y:0,

   SEA_RADIUS:600,
   SEA_LENGTH:800,
   //SEA_ROTATION_SPEED:0.006,
   WAVES_MIN_AMP : 5,
   WAVES_MAX_AMP : 20,
   WAVES_MIN_SPEED : 0.001,
   WAVES_MAX_SPEED : 0.003,

   CAMERA_FAR_POS:500,
   CAMERA_NEAR_POS:150,
   CAMERA_SENSITIVTY:0.002,

   COIN_DISTANCE_TOLERANCE:15,
   COIN_VALUE:3,
   COINS_SPEED:.5,
   COIN_LAST_SPAWN:0,
   DISTANCE_FOR_COINS_SPAWN:100,

   ENEMY_DISTANCE_TOLERANCE:10,
   ENEMY_VALUE:10,
   ENEMIES_SPEED:.6,
   ENEMY_LAST_SPAWN:0,
   DISTANCE_FOR_ENEMIES_SPAWN:50,
};

module.exports = GAME;